region = "eu-cental-1"
worker_instance_type = "t2.small"
server_instance_type = "t2.small"
executor_type = "CeleryExecutor"
server_ami = "ami-0c566a5be0ce1d3b4"
worker_ami = "ami-0ba509ad90b7e66f1"
aws_key_path = "~/.aws/aurimasgriciunastest.pem"
